"""Добавлена таблица рефреш токенов

Revision ID: cf9d71bfc9d5
Revises: d406f083d116
Create Date: 2025-12-11 18:51:48.938831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9d71bfc9d5'
down_revision: Union[str, Sequence[str], None] = 'd406f083d116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
    # ### end Alembic commands ###
